name: Continuous Deployment

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    # Add any backend/database migration scripts here

    - name: Deploy to production
      run: |
        # Your script or command to deploy the application
        # This might be a FTP upload, SSH command, integration with cloud services, etc.